package settings

const (
	SCALE               = 2
	WINDOW_WIDTH        = 800
	WINDOW_HEIGHT       = 600
	INVENTORY_SLOT_SIZE = 30
	INVENTORY_GAP       = 4
	WALL_SPRITE_SIZE    = 32
	BACKGROUND_WIDTH    = 320
	BACKGROUND_HEIGHT   = 240
)
